<?php
use bigwhoop\NBATitleBelt\Team;
use bigwhoop\NBATitleBelt\Game;
use bigwhoop\NBATitleBelt\GameLog;
use bigwhoop\NBATitleBelt\BeltGame;
use bigwhoop\NBATitleBelt\TeamStats;

/** @var array $availableSeasons */
$availableSeasons  = $this->get('availableSeasons');

/** @var GameLog $gameLog */
$gameLog           = $this->get('gameLog');

/** @var Team $beltHolder */
$beltHolder        = $this->get('beltHolder');

/** @var Team $lastYearsNBAChamp */
$lastYearsNBAChamp = $availableSeasons[$this->get('season')]['defendingChamp'];

/** @var Team|null $thisYearsNBAChamp */
$thisYearsNBAChamp = array_key_exists($this->get('season') + 1, $availableSeasons)
                   ? $availableSeasons[$this->get('season') + 1]['defendingChamp']
                   : null;

/** @var Game|null $upcomingChampGame */
$upcomingChampGame = $this->get('upcomingGame');

/** @var Game|null $upcomingChampGameIfHomeTeamWins */
$upcomingChampGameIfHomeTeamWins = $this->get('upcomingChampGameIfHomeTeamWins');

/** @var Game|null $upcomingChampGameIfAwayTeamWins */
$upcomingChampGameIfAwayTeamWins = $this->get('upcomingChampGameIfAwayTeamWins');

/** @var bool $isOngoingSeason */
$isOngoingSeason   = $this->get('isOngoingSeason');

/**
 * @param Team $team
 * @return string
 */
function getTeamLogoURL(Team $team) {
    return '/img/teams/' . $team->getID() . '.gif';
}

/**
* @param Team $team
* @return string
 */
function getTeamLogoLargeURL(Team $team) {
    return 'img/teams-large/' . $team->getID() . '.png';
}

/**
 * @param Team $team
 * @return string
 */
function getTeamLogoImgTag(Team $team) {
    return '<img src="' . getTeamLogoURL($team) . '" alt="' . $team->getID() . '">';
}

/**
 * @param Team $team
 * @return String
 */
function getTeamStadiumBg(Team $team) {
    return 'background-image: linear-gradient(rgba(255, 255, 255, 0.7),rgba(255, 255, 255, 0.3)), url('. "'" . "/img/stadiums/" . $team->getID() . ".jpg');";
}

function getTeamSignature(Team $team) {
    return sprintf(
        '<img src="%s" alt="%s" title="%s"> <span title="%s">%s</span>',
        getTeamLogoURL($team),
        $team->getName(),
        $team->getName(),
        $team->getName(),
        $team->getID()
    );
}


/**
 * @param int|string $season
 * @return string
 */
function getSeasonName($season) {
    if ($season === 'all') {
        return 'All-Time';
    }
    return $season . '-<span class="second-year">' . substr($season + 1, 2) . "</span>";
}
?>
<html>

<head>
    <meta charset="utf-8">
        <title>NBA Championship Belt <?= getSeasonName($this->get('season')); ?> </title>

        <!-- web fonts -->
        <!-- content font-->
        <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
        <!-- header font -->
        <link href='http://fonts.googleapis.com/css?family=Oswald' rel='stylesheet' type='text/css'>

        <link href="/css/stylesheet.css" rel='stylesheet' type='text/css'>
        <link href="/css/deepdata.css" rel='stylesheet' type='text/css'>
        <link href="/css/beltholder-gradients.css" rel='stylesheet' type='text/css'>
        <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
</head>

<body>

    <!-- Top header -->
    <header id='logo-container'>
        <img src="/img/logo.png" class='logo'>
        <div class='current-season'><?= getSeasonName($this->get('season')); ?></div>
        <div class='past-seasons'>
            <?php foreach (array_keys($availableSeasons) as $season): ?>
                <?php if ($season === 'all') { continue; } ?>
                <?php if ($season == $this->get('season')): ?>
                    <?= getSeasonName($season); ?>
                <?php else: ?>
                    <a href="?season=<?= $season; ?>"><?= getSeasonName($season); ?></a>
                <?php endif; ?>
            <?php endforeach; ?>
        </div>
    </header>

    <!-- White area, with current champs and next game -->
    <div id='content-container'>
        <?php $team=$beltHolder->getID() ?>

        <!-- Holder of current belt container -->
        <div id='belt-holder' class='<?= $team?>'>
            <header><i class="fa fa-trophy"></i>
                <?php if ($isOngoingSeason): ?>
                    HOLDER OF CHAMPION BELT
                <?php else: ?>
                    WINNER OF CHAMPION BELT
                <?php endif; ?>
            </header>
            <div class='result'>
                <img src="/img/teams-large/<?= $team?>.png" class='team-large-logo'>
                <footer><?= $team?></footer>
            </div>
        </div>

        <?php if ($upcomingChampGame): ?>
        <? $away_team = $upcomingChampGame->getAwayTeam(); ?>
        <? $home_team = $upcomingChampGame->getHomeTeam(); ?>

         <!-- Next battle of the belt -->
        <div id='next-battle'>
            <header><i class="fa fa-forward"></i> NEXT BATTLE FOR THE BELT </header>
            <div class='content' style="<?= getTeamStadiumBg($upcomingChampGame->getHomeTeam()); ?>">
                <div class='team away'>
                    <img src=<?= getTeamLogoLargeURL($upcomingChampGame->getAwayTeam()); ?> class='team-large-logo'>
                    <footer><?= $away_team->getName(); ?></footer>
                </div>
                <div class='atsign'>
                    @
                </div>
                <div class='team home'>
                    <img src=<?= getTeamLogoLargeURL($upcomingChampGame->getHomeTeam()); ?> class='team-large-logo'>
                    <footer><?= $home_team->getName(); ?></footer>
                </div>
                <div class='date'>
                    <?= $upcomingChampGame->getDate()->format('l M d, Y'); ?>
                </div>
            </div>
        </div>

        <?php endif; ?>
    </div>

    <!-- Bottom half of page -->
    <div id='stats-container'>
        <div class='container'>
            <div id='meta-info'>
                <!-- Rules of the belt -->
                <div class='rules'>
                    <header> <i class="fa fa-bolt"></i> RULES</header>
                    <section>
                        It starts with the first game of last season's NBA champion.<br><br>
                        If the belt holding team gets beat it loses the belt to the other team.<br><br>
                        No playoffs, the race is over after the regular season.
                    </section>
                </div>

                <!-- credit! -->
                <div class='sources'>
                    <header><i class="fa fa-hand-o-right"></i> DATA SOURCES</header>
                    <section>
                        <div class='label'>Idea:</div><a href="http://www.reddit.com/r/nba/comments/1pn9t2/can_we_keep_track_of_the_owner_of_the/">/u/hckygod91 on reddit</a><br>
                        <div class='label'>Scores: </div><a href="http://www.basketball-reference.com/">basketball-reference.com</a><br>
                        <div class='label'>Logos: </div><a href="http://www.nba.com/">nba.com</a><br>
                        <div class='label'>Contribute:</div><a href="https://github.com/bigwhoop/nbachampionshipbelt">bigwhoop/nbachampionshipbelt</a>
                    </section>
                </div>
            </div>

            <!-- Data Tables -->
            <div id='table-data-container'>
                <header class='header'>
                    <i class="fa fa-arrow-circle-o-down"></i> STATS
                </header>
                <!-- Link to switch -->
                <header class='table-functions'>
                    <div class='table-view'>
                        <a class='selected' id="standings-link">Standings</a> <a id="game-log-link">Game Log</a>
                    </div>
                </header>

                <!-- Table container -->
                <div class='content'>
                    <!-- GAME LOG -->
                    <table id='game-log' class='hide'>
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Date</th>
                                <th>Matchup</th>
                                <th>Score</th>
                                <th>Winner</th>
                                <th>Streak</th>
                                <th>Wins</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($gameLog as $idx => $beltGame): ?>
                                <?php
                                /** @var BeltGame $beltGame */
                                $game = $beltGame->getGame();
                                $newBeltHolder = $beltGame->getBeltHolderAfterGame();
                                ?>
                                <tr>
                                    <td><?= $idx + 1; ?></td>
                                    <td><?= $game->getDate()->format('Y-m-d'); ?></td>
                                    <td><?= $game->getHomeTeam()->getID(); ?> @ <?= $game->getAwayTeam()->getID(); ?></td>
                                    <td><?= $game->getScore();; ?></td>
                                    <td><?= getTeamLogoImgTag($newBeltHolder); ?> <?= $newBeltHolder->getID(); ?></td>
                                    <td><?= $beltGame->getWinStreak(); ?></td>
                                    <td><?= $beltGame->getAccumulatedWins(); ?></td>
                            <?php endforeach; ?>
                        </tbody>
                    </table>

                    <!-- STANDINGS -->
                    <table id='standings'>
                        <thead>
                            <tr>
                                <th rowspan="2">Rank</th>
                                <th rowspan="2">Team</th>
                                <?php if ($this->get('season') === 'all'): ?>
                                    <th rowspan="2" class="numeric"><small>Alt. Names</small></th>
                                <?php endif; ?>
                                <th rowspan="2" class="numeric">Games</th>
                                <th colspan="3" class="numeric subth">Wins</th>
                                <th colspan="3" class="numeric subth">Losses</th>
                                <th rowspan="2">Win %</th>
                            </tr>
                            <tr>
                                <th class="numeric">Total</th>
                                <th class="numeric"><small title="As Challenger">As Chall.</small></th>
                                <th class="numeric"><small title="As Defender">As Def.</small></th>
                                <th class="numeric">Total</th>
                                <th class="numeric"><small title="As Challenger">As Chall.</small></th>
                                <th class="numeric"><small title="As Defender">As Def.</small></th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php $rank = 1; $prevWinPercentage = $prevNumGames = null; ?>
                            <?php foreach ($this->get('stats') as $teamStats): ?>
                                <?php /** @var TeamStats $teamStats */ ?>
                                <tr>
                                    <td>
                                        <?php
                                            $numGames = $teamStats->countGames();
                                            $winPercentage = $teamStats->calcWinPercentage();

                                            if ($prevWinPercentage !== $winPercentage || $prevNumGames !== $numGames) {
                                                echo $rank . '.';
                                                $prevNumGames = $numGames;
                                                $prevWinPercentage = $winPercentage;
                                            }
                                            $rank++;
                                        ?>
                                    </td>
                                    <td><?= getTeamSignature($teamStats->getTeam()); ?></td>
                                    <?php if ($this->get('season') === 'all'): ?>
                                        <td><small><?= join('<br>', $teamStats->getTeam()->getAlternativeNames()); ?></small></td>
                                    <?php endif; ?>
                                    <td class="numeric"><?= $numGames; ?></td>
                                    <td class="numeric"><?= $teamStats->countWins(); ?></td>
                                    <td class="numeric"><small><?= $teamStats->countWinsAsChallenger(); ?></small></td>
                                    <td class="numeric"><small><?= $teamStats->countWinsAsDefender(); ?></small></td>
                                    <td class="numeric"><?= $teamStats->countLosses(); ?></td>
                                    <td class="numeric"><small><?= $teamStats->countLossesAsChallenger(); ?></small></td>
                                    <td class="numeric"><small><?= $teamStats->countLossesAsDefender(); ?></small></td>
                                    <td><?= $winPercentage; ?>%</td>
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <!-- For switching between game log/standings -->
    <script type="text/javascript">
    (function() {
        function _selectGameLog() {
            document.getElementById("game-log-link").className = 'selected';
            document.getElementById("game-log").className = '';
            document.getElementById("standings-link").className = '';
            document.getElementById("standings").className = 'hide';
        }
        function _selectStandings() {
            document.getElementById("game-log-link").className = '';
            document.getElementById("game-log").className = 'hide';

            document.getElementById("standings-link").className = 'selected';
            document.getElementById("standings").className = '';
        }
        document.getElementById("game-log-link").addEventListener("click", _selectGameLog);
        document.getElementById("standings-link").addEventListener("click", _selectStandings);
    })();
    </script>
</body>
</html>